# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      RepoName:
        required: true
      BranchName:
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Jenkinsfile-run:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: parent repo checkout
        uses: actions/checkout@v2
      - name: Child repo checkout
        uses: actions/checkout@v2
        with:
            repository: "${{ github.event.inputs.RepoName }}"
            ref: "${{ github.event.inputs.BranchName }}"
            token: ${{ secrets.ACCESS_TOKEN }}
            path: "${{ github.event.inputs.RepoName }}"
    # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          pwd
          ls -lart
          cd ..
          wget https://github.com/jenkinsci/jenkinsfile-runner/releases/download/1.0-beta-30/jenkinsfile-runner-1.0-beta-30.zip
          unzip jenkinsfile-runner-1.0-beta-30.zip
          pwd
          chmod u+x ./bin/jenkinsfile-runner
          ls -lart
          pwd
          wget https://get.jenkins.io/war/2.342/jenkins.war
          pwd
          cp /home/runner/work/CodeScanning_Test/CodeScanning_Test/"${{ github.event.inputs.RepoName }}"/properties.jenkins /home/runner/work/CodeScanning_Test/CodeScanning_Test
          ls -lart
          ./bin/jenkinsfile-runner -w /home/runner/work/CodeScanning_Test/jenkins.war -p /home/runner/work/CodeScanning_Test/CodeScanning_Test/plugins.txt -f /home/runner/work/CodeScanning_Test/CodeScanning_Test/jenkinsfile -ns
          
      #- name: Jenkinsfile Runner Prepackaged
      # You may pin to the exact commit or the version.
      # uses: jenkinsci/jenkinsfile-runner-github-actions@28b21582b55af29ca1e76329b0a48aa3843c5d
      #uses: jenkinsci/jenkinsfile-runner-github-actions@v0.2
